#pragma once

#include <optional>
#include <string>
#include <string_view>
#include <vk_mem_alloc.h>
#include <lib/lib.hpp>

#include "VulkanCore.hpp"

namespace ptvc::rhi
{
    class Device;

    struct ImageCreateInfo
    {
        vk::Extent2D            extent;
        vk::ImageUsageFlags     usageFlags;
        vk::Format              format;
        bool                    mipmapping  = true;
        vk::SampleCountFlagBits samples     = vk::SampleCountFlagBits::e1;
        std::string_view        label       = "Unknown Image";
        SPtr<Device>            device      = nullptr;
    };

    /**
     * Wrapper class for a 2D Image
     */
    class Image
    {
    public:
        DISABLE_COPY(Image);

        [[nodiscard]] static Result<SPtr<Image>> create(const ImageCreateInfo& createInfo) noexcept;

        /**
         * Generate the mipmaps for the image, this requires a CommandBuffer as the mip chain is generated by blitting.
         * @note Mipmaps must be generated before the first use of the Image.
         * @param commandBuffer Recording CommandBuffer
         * @param srcState (Optional) Source state for image memory barriers. (Default: Undefined -> ...)
         * @param dstState (Optional) Destination state for image memory barriers. (Default: ... -> ShaderReadOnly)
         */
        void generateMipmaps(const vk::CommandBuffer& commandBuffer,
            const std::optional<ImageState>& srcState = std::nullopt,
            const std::optional<ImageState>& dstState = std::nullopt) const noexcept;

        [[nodiscard]] vk::Image getHandle() const noexcept;

        [[nodiscard]] vk::ImageView getImageView() const noexcept;

        [[nodiscard]] const ImageProperties& getProperties() const noexcept;

    private:
        explicit Image(const ImageCreateInfo& createInfo);

        [[nodiscard]] Result<void> create_Image(const ImageCreateInfo& createInfo) noexcept;

        const ImageProperties   mProperties;
        const std::string       mLabel;

        vk::Image               mImage;
        vk::ImageView           mImageView;
        VmaAllocation           mAllocation {};
        VmaAllocationInfo       mAllocationInfo {};

        SPtr<Device>            mDevice;
    };
}
